version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ./server/config/config.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${INIT_DB}
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    env_file:
      - ./server/config/config.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 5000:5000
    links:
      - mongo-database 
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
volumes:
  mongo-data:
    driver: local
